name: Build with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: webhook-solver-jar
        path: target/webhook-solver-0.0.1-SNAPSHOT.jar
